// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFtb8slzWLKq3O-OMso5_rq0l5nc2XkeI',
    appId: '1:702958944935:web:2fe6eab373dea2af535182',
    messagingSenderId: '702958944935',
    projectId: 'booklibary-1849f',
    authDomain: 'booklibary-1849f.firebaseapp.com',
    storageBucket: 'booklibary-1849f.firebasestorage.app',
    measurementId: 'G-GZBWRXFD24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_TwjdcWyki5bLt7LHtt-KP5SBYuHGaME',
    appId: '1:702958944935:android:cdcf761a4374dcb9535182',
    messagingSenderId: '702958944935',
    projectId: 'booklibary-1849f',
    storageBucket: 'booklibary-1849f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJohCPza80Gf94w4iHsqeT4JXQ1jEKrRw',
    appId: '1:702958944935:ios:f91633657ff72d8d535182',
    messagingSenderId: '702958944935',
    projectId: 'booklibary-1849f',
    storageBucket: 'booklibary-1849f.firebasestorage.app',
    iosBundleId: 'com.example.bookLibary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJohCPza80Gf94w4iHsqeT4JXQ1jEKrRw',
    appId: '1:702958944935:ios:f91633657ff72d8d535182',
    messagingSenderId: '702958944935',
    projectId: 'booklibary-1849f',
    storageBucket: 'booklibary-1849f.firebasestorage.app',
    iosBundleId: 'com.example.bookLibary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFtb8slzWLKq3O-OMso5_rq0l5nc2XkeI',
    appId: '1:702958944935:web:2870e19fe9ed46cb535182',
    messagingSenderId: '702958944935',
    projectId: 'booklibary-1849f',
    authDomain: 'booklibary-1849f.firebaseapp.com',
    storageBucket: 'booklibary-1849f.firebasestorage.app',
    measurementId: 'G-V9SG6JTSZP',
  );
}
